performance:
    SpreadOperator:
        active: false

libraries:
    LibraryEntitiesShouldNotBePublic:
        active: false

formatting:
    MaximumLineLength:
        maxLineLength: 200

style:
    MaxLineLength:
        maxLineLength: 200
