performance:
    SpreadOperator:
        active: false

libraries:
    LibraryEntitiesShouldNotBePublic:
        active: false

formatting:
    MaximumLineLength:
        maxLineLength: 200

style:
    MaxLineLength:
        maxLineLength: 200
    VarCouldBeVal:
        ignoreLateinitVar: true
    ForbiddenImport:
        active: true
        imports: []
        forbiddenPatterns: 'org\.junit\.jupiter\.api\.Assertions|org\.hamcrest'
    ForbiddenMethodCall:
        active: true
        methods:
            - 'kotlin.assert'
            - 'org.junit.jupiter.api.Assertions.assertEquals'
            - 'org.junit.jupiter.api.Assertions.assertTrue'
            - 'org.junit.jupiter.api.Assertions.assertFalse'
            - 'org.junit.jupiter.api.Assertions.assertNull'
            - 'org.junit.jupiter.api.Assertions.assertNotNull'
            - 'org.junit.jupiter.api.Assertions.assertArrayEquals'
            - 'org.junit.jupiter.api.Assertions.assertIterableEquals'
            - 'org.junit.jupiter.api.Assertions.assertNotEquals'
            - 'org.junit.jupiter.api.Assertions.assertSame'
            - 'org.junit.jupiter.api.Assertions.assertNotSame'
            - 'org.junit.jupiter.api.Assertions.assertAll'
            - 'org.junit.jupiter.api.Assertions.assertThrowsExactly'
